version: 0.2.1.{build}

services:
#  - mssql2008r2sp2
  - mssql2014
  - mysql

image: Visual Studio 2015

platform:
#  - x86
  - x64
  
configuration:
  - Debug
  - Release

environment:
  MYSQL_DIR: C:\Program Files\MySql\MySQL Server 5.7
  VS_VERSION: 14 2015
#  matrix:
#  - VS_VERSION: 14 2015
#    VS_PLATFORM: x86
#    MYSQL_DIR: C:\Program Files\MySql\MySQL Server 5.7
#  - VS_VERSION: 14 2015
#    VS_PLATFORM: x64
#    MYSQL_DIR: C:\Program Files\MySql\MySQL Server 5.7

branches:
  only:
    - master
    - develop

install:
  - git clone https://github.com/snikulov/sqlite.cmake.build.git C:\projects\sqlite\src
#  - cinst: nsis

before_build:
  - cd C:\projects\sqlite\src
  - mkdir build.%BDIR%
  - cd build.%BDIR%
  - set SQLITE_ROOT=C:\projects\sqlite\sqlite.%BDIR%
  - mkdir build
  - cd build
  - set PATH=%PATH%;%SQLITE_ROOT%\bin;%MYSQL_DIR%\bin;%MYSQL_DIR%\lib
  - set MYSQL_PWD=Password12!
  - set USER=root
  - mysql -e "create database oos_test;" --user=root
  - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE oos_test"
  - cmake .. -G"Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% -DCMAKE_INSTALL_PREFIX=C:\projects\sqlite\sqlite.%BDIR%
  - cmake --build . --config %PRJ_CFG% --target install

build_script:
  - cd C:\projects\oos
  - cmake -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% -DOOS_ODBC=true -DMSSQL_CONNECTION_STRING:STRING="mssql://sa:Password12!@(local)\\SQL2014/oos_test" -DOOS_SQLITE3=true -DOOS_MYSQL=true -DMYSQL_CONNECTION_STRING:STRING="mysql://root:Password12!@localhost/oos_test" ..
  
build:
  project: C:\projects\oos\build\oos.sln

test_script:
  - cd C:\projects\oos\build && if %CONFIGURATION%==Debug (ctest --verbose -E perftest --build-config %CONFIGURATION%) else (ctest --verbose --build-config %CONFIGURATION%)
